# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis
    
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
  cart.api:
    image: cartapi
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile
