version: '3.4'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis
    
  rabbitmq:
    image: rabbitmq:3-management-alpine


  orderdb:
    image: mcr.microsoft.com/mssql/server

  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile


  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: src/ApiGateWays/OcelotGateWay/Dockerfile


  traditionalwebclient:
    image: ${DOCKER_REGISTRY-}traditionalwebclient
    build:
      context: .
      dockerfile: src/WebClient/TraditionalWebClient/Dockerfile

