version: '3.4'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile
